services:
  grafana:
    image: grafana/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_LOG_LEVEL: debug
      GF_SERVER_ROUTER_LOGGING: true
    ports:
      - 3000:3000/tcp
    volumes:
      - ./tests/provisioning:/etc/grafana/provisioning
      - ./tests/dashboards:/var/lib/grafana/dashboards

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:2.6.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  var-lib-grafana:
