name: CI
on:
  push:
    branches:
      - main
      - publish-image

# These permissions are needed to assume roles from Github's OIDC.
permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name:  Image tag
        id: image-tag
        run: echo "version=$(./image-tag)" >> $GITHUB_OUTPUT

      - name: Build and push to GAR
        uses: grafana/shared-workflows/actions/push-to-gar-docker@main
        id: push-to-gar
        with:
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          tags: |
            "${{ steps.image-tag.outputs.version }}"
            "latest"
          image_name: "mcp-grafana"
          environment: "dev"